### ISSUE TITLE
Changer l'ordre des tabulations

### ISSUE THREAD

**Issue by SteeveDroz** [Marcelo0andrade/TreeFractalePousuite#1]
Lorsqu'on appuie sur la touche `TAB`, l'ordre des éléments sélectionnés est :

1. Générer
1. Niveau de feuilles
1. Saison
1. Angle B
1. Longueur des branches B
1. Angle A
1. Longeur des branches A

Il serait plus logique d'avoir un ordre cohérent.

**Comment by Marcelo0andrade** [comment]
Un ordre logique à été ajouté. cependant , pendant que vous changez de valeur, le focus est envoyé au bouton "Générer", et cela est fait exprès.

**Comment by Marcelo0andrade** [comment]
corrigé dans 4836a95c92b1e02a6e9101a96ba2a8531147c411
