### ISSUE TITLE
Inverser les champs "A" et "B"

### ISSUE THREAD

**Issue by SteeveDroz** [Marcelo0andrade/TreeFractalePousuite#2]
Les champs "Angle A" et "Longueur des branches A" sont à droite, alors que "Angle B" et "Longueur des branches B" sont à gauche. Il faudrait inverser les deux champs, ça serait plus logique pour l'ordre de lecture.

**Comment by Marcelo0andrade** [comment]
Corrigé, merci.

**Comment by SteeveDroz** [comment]
Texte correct: 

> Corrigé dans 4836a95c92b1e02a6e9101a96ba2a8531147c411

Action correcte: fermer l'issue.
