### ISSUE TITLE
Le logiciel ne répond pas lorsque le niveau de feuilles est trop important

### ISSUE THREAD

**Issue by SteeveDroz** [Marcelo0andrade/TreeFractalePousuite#3]
En mettant "Longueur des branches B" à 0.80 et "Niveau de feuilles" à 20, il peut arriver que le logiciel s'arrête et recommence son calcul depuis le début.

**Comment by Marcelo0andrade** [comment]
Merci, Cela vient d'être amélioré. une sorte de "plafond" à été défini.

**Comment by Marcelo0andrade** [comment]
corrigé dans edf0f0cc09d7801c823e71f1ff28248400a4e48c
